backend:
  name: github
  repo: Dami-Senpaiii/techindex
  branch: main
  base_url: "/"
  auth_endpoint: "/oauth"

media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - label: "Beitr√§ge"
    name: "posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    path: "{{fields.tag}}/{{slug}}/index"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Kategorie", name: "tag", widget: "select", options: ["Hardware", "Software", "Fotografie", "Preisvergleich"] }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Titelbild", name: "image", widget: "image" }
      - { label: "Untertitel", name: "subtitle", widget: "string", required: false }
      - { label: "Teaser", name: "excerpt", widget: "text", required: false }
      - { label: "Text", name: "body", widget: "markdown" }
